config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[new create edit update]
  resources :running_records, only: %i[new create edit index update destroy]
  resource :training_suggestions, only: %i[new create show edit update]
  
  get "start" => "top_pages#start"
  get "tutorial" => "top_pages#tutorial"
  
  get "terms" => "static_pages#terms"
  get "privacy" => "static_pages#privacy"

  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_before_login.html.slim
header#header
  .dropdown
    .menu
      .menu-title
        h5 メニュー一覧
      .sub-menu
        ul
          li = link_to t('.start'), start_path
          li = link_to t('.new_user'), new_user_path
          li = link_to t('defaults.login'), login_path
          li = link_to t('.tutorial'), tutorial_path
  nav
    ul#g-navi
      li = link_to 'login', login_path

    = javascript_pack_tag 'header', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'header', 'data-turbolinks-track': 'reload'

app/views/shared/_flash_message.html.slim
- flash.each do |key, value|
  .d-flex.mb-4
  = content_tag(:div, value, class: "alert alert-#{key}")

app/views/shared/_footer.html.slim
footer.pt-2.bg-dark.text-light
  .container.text-center
    ul.nav.justify-content-center
      li.nav-item
        =link_to '利用規約', terms_path, class: 'nav-link link secondary'
      li.nav-item
        =link_to 'プライバシーポリシー', privacy_path, class: 'nav-link link secondary'
      li.nav-item
        a.nav-link.link.secondary href="#" お問い合わせ
    small.text-right
      a.link.secondary href="https://icons8.com" Favicon icon by Icons8

app/views/shared/_header.html.slim
header#header
  .dropdown
    .menu
      .menu-title
        h5 メニュー一覧
      .sub-menu
        ul
          -if @user
            li = link_to t('.edit_user'), edit_user_path(@user)
          li = link_to t('.new_record'), new_running_record_path
          li = link_to t('.index_record'), running_records_path
          li
            - if @training_suggestion.blank?
              = link_to t('.new_training'), new_training_suggestions_path
            - else
              = link_to t('.edit_training'), edit_training_suggestions_path
          li = link_to t('.tutorial'), tutorial_path
  h1 Runner's High
  nav
    ul#g-navi
      li = link_to 'logout', logout_path, method: :delete

    = javascript_pack_tag 'header', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'header', media: 'all', 'data-turbolinks-track': 'reload'

app/views/shared/_modal.html.slim
i.fas.fa-question-circle data-bs-toggle="modal" data-bs-target="#exampleModal"
#exampleModal.modal tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"
  .modal-dialog role='document'
    .modal-content
      .modal-header
        h3
          #exampleModalLabel.modal-title 練習強度
      .modal-body
        .row.justify-content-center
          .col-12.text-start
            h5 E(Easy) : イージーペース
            .progress.mb-3
              .progress-bar role='progressbar' style='width: 100%' aria-valuenow='100' aria-valuemin='0' aria-valuemax='100'
            ul
              li 無理の少ない範囲でのトレーニングで、怪我に対する耐性を作ることができる
              li 推奨時間: 30分以上

            h5 M(Marathon) : マラソンペース
            .progress.mb-3
              .progress-bar.bg-info role='progressbar' style='width: 100%' aria-valuenow='100' aria-valuemin='0' aria-valuemax='100'
            ul
              li マラソンの設定ペースで走るトレーニング
              li 推奨時間: なし

            h5 T(Threhold) : 閾値ペース
            .progress.mb-3
              .progress-bar.bg-success role='progressbar' style='width: 100%' aria-valuenow='100' aria-valuemin='0' aria-valuemax='100'
            ul
              li 持久力を向上させるのに有効なトレーニング
              li 推奨時間: 20~30分

            h5 I(Interval) : インターバル
            .progress.mb-3
              .progress-bar.bg-warning role='progressbar' style='width: 100%' aria-valuenow='100' aria-valuemin='0' aria-valuemax='100'
            ul
              li 有酸素能力の向上を図るためのトレーニング
              li 推奨時間: run 3~5分 + rest 数分 × 3~10セット
            h5 R(Repetition) : レペティション
            .progress.mb-3
              .progress-bar.bg-danger role='progressbar' style='width: 100%' aria-valuenow='100' aria-valuemin='0' aria-valuemax='100'
            ul
              li 無酸素能力、ランニングエコノミーの向上を図るトレーニング
              li 推奨時間: 2分以内 + rest run時間の2~4倍 × 3~10セット