config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[new create edit update]
  resources :running_records, only: %i[new create edit index update destroy]
  resource :training_suggestions, only: %i[new create show edit update]
  
  get "start" => "top_pages#start"
  get "tutorial" => "top_pages#tutorial"
  
  get "terms" => "static_pages#terms"
  get "privacy" => "static_pages#privacy"

  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => "user_sessions#create"
  delete 'logout' => 'user_sessions#destroy', :as => :logout

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/running_record.rb
class RunningRecord < ApplicationRecord
  belongs_to :user

  validates :running_distance, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }, presence: true
  validates :running_hour, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 8 }, presence: true
  validates :running_minute, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 59 }, presence: true
  validates :running_second, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 59 }, presence: true
  validates :freq, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 100 }, presence: true

  enum intensity: { E: 0, M: 1, T: 2, I: 3, R: 4 }
  enum status: { close: 0, open: 1 }
  
end

app/controllers/running_records_controller.rb
class RunningRecordsController < ApplicationController
  before_action :set_running_record, only: %i[edit update destroy]

  def new
    @running_record = RunningRecord.new
  end

  def index
    @user = User.find(current_user.id)
    month_records = @user.running_records.order(date: :desc)
    @month_records = []
    month_records.each do |month_record|
      if month_record.date.between?(Date.today - 30.day, Date.today) # 今日の日付から一週間以内の記録だけを抽出
        @month_records << month_record
      end
    end

    @running_records = current_user.running_records.order(date: :desc)
    gon.vdot = []
    gon.date = []
    gon.user_vdot = current_user.vdot
    @running_records.each do |running_record|
      if judge_intensity(running_record) && running_record.status == 'open'
        gon.vdot << running_record.vdot
        gon.date << running_record.date
      end
    end
    @running_records = current_user.running_records.order(date: :desc).page(params[:page]).per(10)
  end

  def create
    @running_record = current_user.running_records.build(running_record_params)
    if @running_record.save
      @running_record.freq_limit
      redirect_to running_records_path
      flash[:success] = t(".success")
    else
      flash.now[:danger] = t(".fail")
      render :new
    end

  end

  def edit
    gon.user = @running_record.user
    if current_user == @running_record.user
      render :edit
    else
      flash[:danger] = t('defaults.unpermitted')
      redirect_to running_records_path
    end
  end

  def update
    if @running_record.update(running_record_params)
      @running_record.freq_limit
      redirect_to running_records_path
      flash[:success] = t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :edit
    end
  end

  def destroy
    if @running_record.destroy
      redirect_to running_records_path
      flash[:success] = t('.success')
    else
      redirect_to running_records_path
      flash[:danger] = t('.fail')
    end
  end

  private

  def running_record_params
    params.require(:running_record).permit(:date, :running_hour, :running_minute, :running_second, :running_distance, :intensity, :freq, :status)
  end

  def set_running_record
    @running_record = current_user.running_records.find(params[:id])
  end
  
end

app/helpers/running_records_helper.rb
module RunningRecordsHelper
end

app/views/running_records/edit.html.slim
- content_for(:title, t('.edit_record'))
.px-4.pt-5.text-center.border-bottom.fw-bold
  h1.display-4.fst-italic = t('.edit_record')
  .col-sm-8.mx-auto
    = form_with model: @running_record, local: true do |f|
      .row.mb-3
        = f.label :date, class: 'col-5'
        .col-7.d-flex.mx-auto
          = f.date_select :date, { use_month_numbers: true },\
           { class: 'form-control', style: 'display: inline-block;width: auto;' }
      .row.mb-3
        = f.label :time, class: 'col-5'
        .col-7.d-flex.mx-auto
          = f.text_field :running_hour, class: 'form-control', placeholder: 'hh'
          | 時間　
          = f.text_field :running_minute, class: 'form-control', placeholder: 'mm'
          | 分
          = f.text_field :running_second, class: 'form-control', placeholder: 'ss'
          | 秒
      .row.mb-3
        = f.label :running_distance, class: 'col-5'
        .col-7.d-flex.mx-auto
          = f.text_field :running_distance, class: 'form-control'
          |  km
      .row.mb-3
        = f.label :intensity, class: 'col-5'
        .col-7.d-flex.mx-auto
          = f.select :intensity, RunningRecord.intensities_i18n.invert, class: 'form-select'
          = render 'shared/modal'
      .row.mb-3
        = f.label :freq, class: 'col-5'
        .col-7.d-flex.mx-auto
          = f.text_field :freq, class: 'form-control'
          |  本
      p.text-secondary ※練習強度が「E/M/T」のとき、本数は1にしてください
      .row.mb-3
        = f.label :status, class: 'col-5'
        .col-7.d-flex.mx-auto
          = f.select :status, RunningRecord.statuses_i18n.invert, class: 'form-select'
      p.text-secondary ※vdotグラフへの表示/非表示を指定します(練習強度「E/M/T」のみ)

      .d-grid.gap-2.d-flex.justify-content-center.mb-5
        = f.submit t('defaults.registration'), class: 'btn btn-outline-primary btn-lg px-4 me-sm-3'

  .overflow-hidden style='max-height: 30vh;'
    .container
      = image_tag "watch.jpg", class: "img-fluid border rounded-3 shadow-lg mb-4", alt: "画像", loading: "lazy"

app/views/running_records/index.html.slim
- content_for(:title, t('.index_record'))
.container.pt-5
  .display-5.fst-italic.my-3
      .table-responsive
          table.table
            tr
              th scope='col' 月間トレーニング数
              td = @month_records.count
              td
                - if @month_records.count >= 15
                  i.fas.fa-crown.px-2 style="color: #DBB400;"
                - elsif @month_records.count >= 10
                  i.fas.fa-crown.px-2 style="color: #C9CACA;"
                - elsif @month_records.count >= 5
                  i.fas.fa-crown.px-2 style="color: #C47022;"
            tr
              th scope='col' 月間走行距離
              td = "#{@month_records.map{|dist| dist.running_distance * dist.freq}.sum.round(2)} km"
              td

.px-4.my-5.text-center.border-bottom.fw-bold
  h1.display-4.fst-italic = t('.index_record')
  - @running_records.each do |running_record|
    .card.bg-light-dark.mb-4
      .card-body
        h4.card-title
          = link_to "日付: #{running_record.date}　距離: #{running_record.running_distance * running_record.freq} km　強度: #{running_record.intensity}",\
           edit_running_record_path(running_record), class: "mx-4"
          = link_to "削除", running_record_path(running_record), method: :delete, data: {confirm: "トレーニング記録を削除します。よろしいですか？"}, class: "btn btn-danger"

canvas#myChart
a
  #one_month.btn.bgleft href='#'
    span 1ヶ月
a
  #three_months.btn.bgleft href='#'
    span 3ヶ月
a
  #six_months.btn.bgleft href='#'
    span 6ヶ月
a
  #one_year.btn.bgleft href='#'
    span 年

= paginate @running_records, theme: 'bootstrap-5'

= javascript_pack_tag 'chart', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'button', 'data-turbolinks-track': 'reload'
= stylesheet_pack_tag 'button', media: 'all', 'data-turbolinks-track': 'reload'

app/views/running_records/new.html.slim
- content_for(:title, t('.new_record'))
.px-4.pt-5.text-center.border-bottom.fw-bold
  h1.display-4.fst-italic = t('.new_record')
  .col-sm-8.mx-auto
    = form_with model: @running_record, local: true do |f|
      .row.mb-3
        = f.label :date, class: 'col-5'
        .col-7.d-flex.mx-auto
          = f.date_select :date, { use_month_numbers: true },\
           { class: 'form-control', style: 'display: inline-block;width: auto;' }
      .row.mb-3
        = f.label :time, class: 'col-5'
        .col-7.d-flex.mx-auto
          = f.text_field :running_hour, class: 'form-control', placeholder: 'hh'
          | 時間　
          = f.text_field :running_minute, class: 'form-control', placeholder: 'mm'
          | 分
          = f.text_field :running_second, class: 'form-control', placeholder: 'ss'
          | 秒
      .row.mb-3
        = f.label :running_distance, class: 'col-5'
        .col-7.d-flex.mx-auto
          = f.text_field :running_distance, class: 'form-control'
          |  km
      .row.mb-3
        = f.label :intensity, class: 'col-5'
        .col-7.d-flex.mx-auto
          = f.select :intensity, RunningRecord.intensities_i18n.invert, class: 'form-select'
          = render 'shared/modal'
      .row.mb-3
        = f.label :freq, class: 'col-5'
        .col-7.d-flex.mx-auto
          = f.text_field :freq, class: 'form-control'
          |  本
      p.text-secondary ※練習強度が「E/M/T」のとき、本数は1にしてください
      .row.mb-3
        = f.label :status, class: 'col-5'
        .col-7.d-flex.mx-auto
          = f.select :status, RunningRecord.statuses_i18n.invert, class: 'form-select'
      p.text-secondary ※vdotグラフへの表示/非表示を指定します(練習強度「E/M/T」のみ)

      .d-grid.gap-2.d-flex.justify-content-center.mb-5
        = f.submit t('defaults.registration'), class: 'btn btn-outline-primary btn-lg px-4 me-sm-3'

  .overflow-hidden style='max-height: 30vh;'
    .container
      = image_tag "watch.jpg", class: "img-fluid border rounded-3 shadow-lg mb-4", alt: "画像", loading: "lazy"